### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-argentina#21]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] l10n_ar_retentions_basic
- [ ] l10n_ar_chart_of_account
- [ ] l10n_ar_point_of_sale
- [ ] l10n_ar_electronic_invoice_storage_rg1361
- [ ] l10n_ar_bank_statement
- [ ] l10n_ar_wsfe_jasper
- [ ] l10n_ar_wsaa
- [ ] l10n_ar_wsfe
- [ ] l10n_ar_sale_order
- [ ] l10n_ar_cash_register
- [ ] l10n_ar_account_payment
- [ ] l10n_ar_perceptions_basic
- [ ] l10n_ar_tax_reports
- [ ] l10n_ar_wsfe_perceptions
- [ ] l10n_ar_account_create_check
- [ ] base_vat_ar
- [ ] l10n_ar_account_check
